### ISSUE TITLE
Feature - Weeks remain

### ISSUE THREAD

**Issue by poudenes** [Miicroo/ha-birthdays#20]
Great great integration!!!

To make it fully complete it would be great to have: weeks remain  as attribute.

Keep up the good work!

**Comment by Miicroo** [comment]
Nice, thanks for the suggestion @poudenes ! Some quick questions so I can tailor the solution a bit better, do you have a lot of birthdays and are all shown in a list, or do you just use the next birthday and want to know how many weeks out that is? Since it is weeks remaining (so state divided by 7) it could be possible to have it templated, and if so also bring in some way of making custom attributes based on a template

**Comment by poudenes** [comment]
The answer is to know how many weeks till the birthday. Templating a sensor is an options. But if it can be integrated in the integrations as attribute would be nicer :)

**Comment by Miicroo** [comment]
Attribute works too, maybe the attribute itself can be a template so that
users can customize their own attributes instead of waiting on new
versions. Will try to see if I can come up with a PR :)

Den tors 3 okt. 2024 19:28Peter Oudenes ***@***.***> skrev:

**Comment by Miicroo** [comment]
PR is on its way! https://github.com/Miicroo/ha-birthdays/pull/21
Will do some final testing and can add the config you need here when it is done :)

**Comment by Miicroo** [comment]
@poudenes v1.1.0 is released now, here is how you should configure it to add a custom templated attribute so you get `weeks_until_birthday` for each birthday. You have to change the birthdays-list though, I just added it so that you can see what it should look like 

```
birthdays:
  config:
    attributes:
      weeks_until_birthday: '{{ ((this.state or -1) / 7) | int }}'
  birthdays:
    - name: 'Frodo Baggins'
      date_of_birth: 1921-09-22
    - name: 'Bilbo Baggins'
      date_of_birth: 1843-09-22
    - name: Elvis
      date_of_birth: 1935-01-08
      icon: 'mdi:music'
```

Let me know if you have any questions!
