### ISSUE TITLE
Cannot be merged, expected a dict

### ISSUE THREAD

**Issue by rikardronnkvist** [Miicroo/ha-birthdays#23]
Getting this errormessage when adding the integraion as a package:
Setup of package 'birthdays' failed: integration 'birthdays' cannot be merged, expected a dict

In the configuration.yaml i include my packages with
```
homeassistant:
  packages: !include_dir_named packages
```

The file packages/birthdays.yaml contains
```
birthdays:
  - name: Abc
    date_of_birth: 1111-22-33
  - name: Xyz
    date_of_birth: 1111-22-33
```

The complete errormessage:

```
ERROR (MainThread) [homeassistant.config] Setup of package 'birthdays' at packages/birthdays.yaml, line 1 failed: integration 'birthdays' cannot be merged, expected a dict
```

Worked just fine until 2024.11 (or maybe it broke in 2024.10, can't really remember).

**Comment by Miicroo** [comment]
@rikardronnkvist Checking! Which version are you using? Might be the new optional schema that is bothering packages, but that is fairly new so depending on version it might not be that

**Comment by rikardronnkvist** [comment]
2024.11

**Comment by Miicroo** [comment]
Sorry, I meant which version of the birthdays integration do you use?

Den fre 15 nov. 2024 06:29Rikard Ronnkvist ***@***.***> skrev:

**Comment by rikardronnkvist** [comment]
Latest via HACS, 1.2.0

**Comment by Miicroo** [comment]
@rikardronnkvist Finally found a solution, based on an old bug in HomeAssistant that had the same problem!
So it seems that the more complex schema introduced in birthdays 1.1.0 messes with the packages logic (but is fine when not using packages).

The solution is to add an extra `birthdays:`-key in there, otherwise the dict won't be named.
A working schema for packages will look like this:
```
birthdays:
  birthdays:
    - name: Abc
      date_of_birth: 1111-22-33
    - name: Xyz
      date_of_birth: 1111-22-33
```
