### ISSUE TITLE
Age in auto-entity card

### ISSUE THREAD

**Issue by hvestbo** [Miicroo/ha-birthdays#24]
How can I show the age of the person in the auto-entity card?

**Comment by Miicroo** [comment]
@hvestbo I haven't done this myself, but I believe you can use auto-entities together with `custom:template-entity-row`.

The code would then look something like this:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: birthdays
      options:
        type: custom:template-entity-row
        name: >
          {{ state_attr(config.entity, 'friendly_name') }}
        state: >
          {{ state_attr(config.entity, 'age_at_next_birthday') }}
```

Note though that this shows how old each person would be at their next birthday. If you want the current age, you would have to create a templated attribute for the birthdays. Let me know if you need any help with that, or if the auto-entities solution isn't working

**Comment by hvestbo** [comment]
That replaces the days until their birthday with their age.
I was thinking more of a name, and age to the left, and days until their birthday to the right

**Comment by Miicroo** [comment]
@hvestbo Hmm, I see. I think it depends on how much you would like to customize the UI. There is an option called `secondary` that will be displayed under the entity name (to the left) that can be set using `custom:template-entity-row`. Here is an example where they customize name, state and secondary: https://community.home-assistant.io/t/auto-entities-customize-displayed-name-and-use-attribute-as-secondary-info/700415/2

If you want even finer control over the UI, I think that a markdown card might do the trick. Haven't been able to test it out yet though.

**Comment by Miicroo** [comment]
@hvestbo Here is an example of a (very rudimentary) table using a markdown card (showing icon, name, current age, days until birthday):

```
type: custom:auto-entities
card:
  type: markdown
  content: |
    | | | Age | Days until birthday |
    | ----- | ----- | ----- | ----- | {% for entity in config.entities %}
      | <ha-icon icon="{{ state_attr(entity.entity, 'icon') }}"></ha-icon> | {{ states[entity.entity].name }} | {{ (state_attr(entity.entity, 'age_at_next_birthday')-1) }} | {{ states[entity.entity].state }} |
    {%- endfor %}
filter:
  include:
    - domain: birthdays
sort:
  method: state
  numeric: true
```
