### ISSUE TITLE
A Birthday With The Month of March Does Not Properly Display

### ISSUE THREAD

**Issue by theplaceilive** [Miicroo/ha-birthdays#26]
I've been successfully using Birthdays with 12 birthday entries defined in my configuration.yaml file. I've been using an auto-entities card with markdown to display the information. This has been working great.

However, I recently added the additional entry as follows. After checking the configuration and restarting Home Assistant the card and data no longer  rendered properly. The data displayed is outside the card border, and some of the raw card YAML is displayed. Removing the new entry shown followed by restarting Home Assistant allowed the card to properly display again... every time.

  - name: 'Rosie'
    date_of_birth: 2024-03-09
    icon: 'mdi:cake-variant-outline'

I've since discovered this issue only happens if the month used is 03. Changing the month for this particular entry to a different value resolves the issue. Changing any of the prior Birthday entries to use the month of 03 also results in the card not rendering properly. It appears using a month of 03 is problematic. None of the other months currently used causes this issue.

Thanks for making Birthdays!

**Comment by Miicroo** [comment]
@theplaceilive Hello! Wow, that is a funky bug indeed! 😅 
I did test some in my local environment but nothing breaks here, so my test is probably not good enough to catch it. Here are the values I used, can you check and see if you see anything that differs from your setup? That would be immensely helpful in catching the bug.

The configuration (using default values and Rosie):
```
birthdays:
  - name: 'Frodo Baggins'
    date_of_birth: 1921-09-22
    attributes:
      phone_number: 123
      days_since_birth: 5
  - name: 'Bilbo Baggins'
    date_of_birth: 1843-09-22
    attributes:
      phone_number: 456
  - name: Elvis
    date_of_birth: 1935-01-08
    icon: 'mdi:music'
    attributes:
      phone_number: 789
  - name: 'Rosie'
    date_of_birth: 2024-03-09
    icon: 'mdi:cake-variant-outline'
```

The auto-entities card:
```
type: custom:auto-entities
filter:
  include:
    - domain: birthdays
card:
  type: entities
  show_header_toggle: false
  title: Birthdays
sort:
  method: state
  numeric: true
```

Here it what it looks like:

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/2abfa7e6-db2c-459f-9c14-ccc9005dac77" />

About the card: Are you using it in panel mode (only auto-entities
 card shown on the entire page) or do you have multiple cards on the same page?

Also, if you feel comfortable, can you check the browser console and see if you get any errors? HomeAssistant tends to be very chatty in the console so there is always a risk that there is too many things being logged, but it doesn't hurt to look
